### ISSUE TITLE
Bug with deleting numbers

### ISSUE THREAD

**Issue by ViktorKahu** [you-apps/ConnectYou#217] opened 2023-08-15 21:45 UTC
### Steps to reproduce

When a contact has multiple numbers stored and I want to delete one, the menu dialogue works, but once changes are saved, the second/third/etc... Number is back. Hence it's currently impossible to get rid of stored numbers.

### Expected behavior

The made changes should be reflected once saved.

### Actual behavior

See above

### Connect You version

6.0

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by ViktorKahu** [comment] 2023-08-19 22:36
Update: it seems the fault was due to multiple instances of the same contacts saved on the device, possibly due to imperfections of the import or backup/restore features. You may want to do some investigating in that direction.

Anyway, after I had to use another contacts app to clean up my contact list, the fault is no longer there and adding/deleting numbers seems to work as intended.

**Comment by M00NJ** [comment] 2023-11-11 18:06
I will close this as completed, since it's not a bug. If you have suggestions on how to improve the backup/restore feature or make it easier to clean up your contacts list from within ConnectYou, please feel free to open a feature request for that.

**Closed by M00NJ** 2023-11-11 18:06 UTC
Labels: bug, can't reproduce
