### ISSUE TITLE
Settings design in some translations

### ISSUE THREAD

**Issue by Artem13327** [you-apps/ConnectYou#261] opened 2023-09-12 15:04 UTC
### Steps to reproduce

-

### Expected behavior

-

### Actual behavior

![Screenshot_20230912-163901](https://github.com/you-apps/ConnectYou/assets/68551925/cbb3785c-ae35-47c0-95b1-10f08b376237)
![Screenshot_20230912-163857](https://github.com/you-apps/ConnectYou/assets/68551925/06b634c3-8e03-4c14-9aa3-7ae2ebbb9fd1)

### Connect You version

6.0

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-09-12 15:38
Duplicate of #219

**Closed by Bnyro** 2023-09-12 15:38 UTC
Labels: bug
