### ISSUE TITLE
Conversations, Priority Conversations and Message Bubbles 

### ISSUE THREAD

**Issue by Wave6677** [you-apps/ConnectYou#335] opened 2023-11-22 08:02 UTC
### Describe your suggested feature

Introduced in Android 11 this feature has always been the deciding factor in choosing a primary client for me, and many others I'm sure. Being able to not have to open the app, while being able to read the chat and respond to messages would be a great feature, especially since the framework is built into android.

Example of Feature: https://developer.android.com/codelabs/android-people#0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by M00NJ** [comment] 2023-11-23 07:54
> this feature has always been the deciding factor in choosing a primary client for me

ConnectYou is not meant to be your primary messenging application. SMS is is a very insecure communication standard and should not be used for chatting. The basic implementation in ConnectYou is meant for receiving automated messages like TANs. The main focus of our app suite is privacy and creating a feature rich SMS messenger would not further this goal. So I'm sorry to disappoint you here, but we will not work on more advanced features that improve chatting, since it's not the intended use case. However if someone wants to contribute a feature like MMS support, we'll probably accept PRs. Offtopic, but consider moving to an encrypted messaging standard for chatting like Signal, Matrix or Briar to protect your privacy.

**Closed by M00NJ** 2023-11-23 07:54 UTC
Labels: enhancement

**Comment by M00NJ** [comment] 2023-11-23 08:03
@ Bnyro we should probably pin this somewhere and just link to it next time. I don't what to explain this every 3 days 😅. Also didn't consider that SMS is more wide spread in other countries (e.g. US).

**Comment by Bnyro** [comment] 2023-11-23 13:31
> @ Bnyro we should probably pin this somewhere and just link to it next time. I don't what to explain this every 3 days 😅.
>
Yes, agreed.

> Also we didn't consider that SMS is more wide spread in other countries (e.g. US).
>
Interesting, didn't know that. In fact nobody should really use this anymore for secure messaging ...

**Comment by Wave6677** [comment] 2023-11-25 22:19
> > this feature has always been the deciding factor in choosing a primary client for me
> 
> ConnectYou is not meant to be your primary messenging application. SMS is a very insecure communication standard and should not be used for chatting. The basic implementation in ConnectYou is meant for receiving automated messages like TANs. The main focus of our app suite is privacy and creating a feature rich SMS messenger would not further this goal. So I'm sorry to disappoint you here, but we will not work on more advanced features that improve chatting, since it's not the intended use case. However if someone wants to contribute a feature like MMS support, we'll probably accept PRs. Offtopic, but consider moving to an encrypted messaging standard for chatting like Signal, Matrix or Briar to protect your privacy.

Hi, this is off topic but I am already someone who uses Signal and Matrix. I understand not wanting people to use SMS, but it's a universal standard in the US still. My bank, job and doctors still use it for 2FA, reminders, and alerts that I have no other option to switch to. I don't like it either, but I wouldn't personally include the feature to read SMS in the first place if you don't want people to use it as SMS, or at the very least adding a closable warning stating the purpose of your SMS feature in app to say "Don't use this, it's not secure, and we don't want you to use this for your messages.".

**Comment by M00NJ** [comment] 2023-11-25 22:38
In your issue you said that the requested features are what you look for in your **_primary messaging client_** and now you say that you only use SMS for recieving reminders from your bank or doctor (which is exactly what this feature was intended for), so what is it now? Why do you want chat bubbles and priority messages for recieving automated messages? You're stating two opposing things here. And if I go by your most recent explanation it seems you're using the SMS feature exactly for what it was intended for.

**Comment by Wave6677** [comment] 2023-11-26 03:01
Client in reference to the spec not to every message I've ever sent. I'm currently using the QKSMS client to send SMS messages. I use the Signal-FOSS client to send Signal messages, and I use the FluffyChat client to send Matrix messages. I'm sorry I didn't use super specific wording to specify I meant SMS client. I want priority and messages bubbles because I want to know if my therapist is texting me to remind me about an appointment immediately. I don't want it buried in my other notifications. If I'm doing something else I don't want to have to switch to another app to confirm that I'll be attending. Its annoying. I'm not stating 2 opposing things, I'm stating that I want a feature that is built into android to make my life easier. I don't see why/how wanting to customize the way I get my notifications for an app, automated or not, is a problem.
